main_node:
  ros__parameters:
    # Robot parameters
    robot_name: "jackal"
    max_lin_vel: 0.5
    min_lin_vel: 0.0
    max_ang_vel: 1.0
    min_ang_vel: -1.0
    robot_type: "rectangular" # rectangular or circular
    robot_radius: 0.3 # [m], If robot_type is cicrular
    robot_size: [0.508, 0.430] #[0.508, 0.430] # [m, m], Lenght, Width if robot_type is rectangular
    collision_tolerance: 0.03 # [m], tollerance of collision added to robot_radius or robot_size
    warning_tolerance: 0.1 # [m], warning window added to robot_radius or robot_size
    goal_tolerance: 0.40

    # World parameters
    world_name: "vineyard.world" #Leave empty to obtain no world
    data_path: "vineyard_straight.json"

    # Task parameters
    task: 'Vineyards' # goToPose, Following, Vineyards
    
    # Sensors parameters
    update_frequency: 20.0
    sensor: 'camera' # lidar or camera
    visual_data: 'features'
    features: 12544
    channels: 1
    imu_enabled: "false"
    camera_enabled: "true"
    stereo_camera_enabled: "false"
    lidar_enabled: "true"
    sensors_topic:
      rgb_topic: "/camera/image_raw"
      depth_topic: "/camera_stereo/depth/image_raw" #"/camera/depth/image_raw"
      laser_topic: "/scan" #scan
      imu_topic: "/imu/data" #imu_data
      odom_topic: "/jackal/ground_truth"
    laser_param:
      max_distance: 10.0 # Meters
      num_points: 36 # int divider of 360
    depth_param:
      dist_cutoff: 5 # Meters
      width: 112
      height: 112
      show_image: False
    rgb_param:
      width: 640
      height: 480
      show_image: False 
